var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
var bike = "BMW";
console.log("Is bike == 'BMW'? I predict True.");
console.log(bike == 'BMW');
var IceCream = "Chocolate";
console.log("Is IceCream == 'Chocolate'? I predict True.");
console.log(IceCream == 'Chocolate');
var age = 25;
console.log("Is age == 25? I predict True.");
console.log(age == 25);
var isTrue = true;
console.log("Is isTrue == true? I predict True.");
console.log(isTrue == true);
var fruit = "banana";
console.log("Is fruit == 'apple'? I predict False.");
console.log(fruit == 'apple');
var bikeModel = "YAMAHA H2R";
console.log("Is bikeModel == 'Harley Davidson'? I predict False.");
console.log(bikeModel == 'Harley Davidson');
var weather = "rainy";
console.log("Is weather == 'sunny'? I predict False.");
console.log(weather == 'sunny');
var isLoggedIn = 0;
console.log("Is isLoggedIn == 1? I predict False.");
console.log(isLoggedIn == 1);
var numPets = 3;
console.log("Is numPets == 5? I predict False.");
console.log(numPets == 5);
